import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { contractAnalyzeChat, contractGenerateDraft } from "@/components/functions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { FileText, AlertCircle, Sparkles, Shield, AlertTriangle, CheckCircle, Scale } from "lucide-react";
import LoadingAnimation from "@/components/LoadingAnimation";

const CONTRACT_TEMPLATES = [
  { id: "buyer_rep_v1", name: "Buyer Representation Agreement" },
  { id: "referral_v1", name: "Referral Agreement" },
  { id: "services_v1", name: "Real Estate Services Agreement" }
];

export default function ContractWizard({ roomId, open, onClose }) {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState(null);
  const [templateId, setTemplateId] = useState("");
  const [terms, setTerms] = useState({});
  const [missing, setMissing] = useState([]);
  const [draft, setDraft] = useState("");
  const [saving, setSaving] = useState(false);
  const [mode, setMode] = useState("ai"); // "ai" or "template"
  const [aiFlowResult, setAiFlowResult] = useState(null);

  useEffect(() => {
    if (!open) return;
    setStep(1);
    setAnalysis(null);
    setTemplateId("");
    setTerms({});
    setMissing([]);
    setDraft("");
    setMode("ai");
    setAiFlowResult(null);
  }, [open]);

  // AI Flow: Generate + Analyze in one step
  const runAiFlow = async () => {
    setLoading(true);
    // Simulate loading delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Use placeholder contract for demo
    const placeholderDraft = `# BUYER REPRESENTATION AGREEMENT

**Generated by AI Contract Flow**

---

## PARTIES

**BUYER (Investor):** [Investor Name]  
**AGENT:** [Agent Name], [Brokerage]

---

## 1. SCOPE OF REPRESENTATION

Agent agrees to represent Buyer in the search, evaluation, negotiation, and acquisition of investment real estate properties in the following markets: [Target Markets].

## 2. PROPERTY CRITERIA

- **Property Types:** Multifamily, Single Family, Commercial
- **Price Range:** $100,000 - $1,000,000
- **Investment Strategy:** Buy & Hold, Value-Add, BRRRR
- **Target Returns:** 8%+ Cash-on-Cash Return

## 3. AGENT DUTIES

Agent agrees to:
- Provide access to on-market and off-market deal flow
- Conduct initial property analysis and due diligence support
- Coordinate property tours and inspections
- Negotiate on behalf of Buyer
- Facilitate transaction through closing

## 4. COMPENSATION

- **Commission:** 2.5-3% of purchase price, paid at closing
- If seller pays commission, no additional fee from Buyer
- **Retainer:** $0 (performance-based only)

## 5. TERM

This Agreement shall remain in effect for 12 months from the date of execution.

## 6. EXCLUSIVITY

Buyer agrees to work exclusively with Agent for properties in the defined markets during the term of this Agreement.

## 7. CONFIDENTIALITY

Both parties agree to maintain confidentiality of all proprietary information shared during the course of this relationship.

## 8. TERMINATION

Either party may terminate this Agreement with 30 days written notice.

---

**SIGNATURES:**

_________________________  
Investor (Buyer)  
Date: _______________

_________________________  
Agent  
Date: _______________

---

*This is a placeholder contract for demonstration purposes.*
`;

    const placeholderAnalysis = {
      overallRisk: 'Low',
      redFlags: [
        'Commission structure should specify exact percentage',
        'Consider adding dispute resolution clause'
      ],
      recommendations: [
        'Add specific termination conditions',
        'Include clause for property inspection contingencies',
        'Specify communication frequency expectations'
      ]
    };

    setAiFlowResult({
      ok: true,
      draft: placeholderDraft,
      analysis: placeholderAnalysis,
      parties: {
        investor: 'Demo Investor',
        agent: 'Demo Agent'
      }
    });
    setDraft(placeholderDraft);
    setAnalysis(placeholderAnalysis);
    setStep(3);
    setLoading(false);
  };

  // Template flow: Analyze first
  const analyze = async () => {
    setLoading(true);
    // Simulate loading delay
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    // Use placeholder data for demo
    const placeholderAnalysis = {
      suggested_template_id: "buyer_rep_v1",
      plain_summary: "Based on your conversation, this appears to be a buyer representation agreement for investment property acquisition. The investor is looking for multifamily properties with a focus on cash flow.",
      terms: {
        "Investor Name": "Demo Investor",
        "Agent Name": "Demo Agent",
        "Brokerage": "Premier Realty Group",
        "Target Markets": "Texas, Florida",
        "Property Types": "Multifamily, Single Family",
        "Price Range": "$200,000 - $800,000",
        "Commission Rate": "3%",
        "Agreement Term": "12 months"
      },
      missing_fields: ["Investor Address", "Agent License Number"]
    };
    
    setAnalysis(placeholderAnalysis);
    setTemplateId(placeholderAnalysis.suggested_template_id);
    setTerms(placeholderAnalysis.terms);
    setMissing(placeholderAnalysis.missing_fields);
    setStep(2);
    setLoading(false);
  };

  const updateTerm = (k, v) => {
    setTerms(prev => ({ ...prev, [k]: v }));
  };

  const generate = async () => {
    if (!templateId) {
      alert("Please select a template");
      return;
    }

    setSaving(true);
    // Simulate loading delay
    await new Promise(resolve => setTimeout(resolve, 1200));
    
    // Generate placeholder contract from template
    const templateName = CONTRACT_TEMPLATES.find(t => t.id === templateId)?.name || "Contract";
    
    const generatedDraft = `# ${templateName.toUpperCase()}

**Generated from Template: ${templateId}**

---

## PARTIES

**BUYER/INVESTOR:** ${terms["Investor Name"] || "[Investor Name]"}  
**AGENT:** ${terms["Agent Name"] || "[Agent Name]"}, ${terms["Brokerage"] || "[Brokerage]"}

---

## 1. PURPOSE

This ${templateName} is entered into for the purpose of establishing a professional relationship between the parties for real estate investment services.

## 2. SCOPE

**Target Markets:** ${terms["Target Markets"] || "[Markets]"}  
**Property Types:** ${terms["Property Types"] || "[Property Types]"}  
**Price Range:** ${terms["Price Range"] || "[Price Range]"}

## 3. COMPENSATION

**Commission Rate:** ${terms["Commission Rate"] || "3%"} of purchase price, payable at closing.

## 4. TERM

This Agreement shall be effective for ${terms["Agreement Term"] || "12 months"} from the date of execution.

## 5. DUTIES AND OBLIGATIONS

### Agent Responsibilities:
- Identify suitable investment properties
- Provide market analysis and due diligence support
- Negotiate on behalf of the investor
- Coordinate inspections and closing

### Investor Responsibilities:
- Provide clear investment criteria
- Respond to opportunities in a timely manner
- Provide proof of funds when required

## 6. CONFIDENTIALITY

Both parties agree to maintain strict confidentiality regarding all proprietary information, deal terms, and financial details shared during this engagement.

## 7. TERMINATION

Either party may terminate this Agreement with 30 days written notice.

---

**SIGNATURES:**

_________________________  
${terms["Investor Name"] || "Investor"}  
Date: _______________

_________________________  
${terms["Agent Name"] || "Agent"}  
License #: ${terms["Agent License Number"] || "_______________"}  
Date: _______________

---

*This is a placeholder contract generated from template for demonstration purposes.*
`;
    
    setDraft(generatedDraft);
    setStep(4);
    setSaving(false);
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <div className="bg-white w-full max-w-3xl rounded-2xl overflow-hidden shadow-2xl">
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <FileText className="w-6 h-6" />
              <h3 className="text-2xl font-bold">Generate Contract</h3>
            </div>
            <button 
              onClick={onClose}
              className="text-white/80 hover:text-white text-xl font-semibold"
            >
              ✕
            </button>
          </div>
        </div>

        <div className="p-6">
          {/* Step 1: Choose Mode */}
          {step === 1 && (
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* AI Flow Option */}
                <button
                  onClick={() => setMode("ai")}
                  className={`p-6 rounded-xl border-2 text-left transition-all ${
                    mode === "ai" 
                      ? "border-blue-500 bg-blue-50" 
                      : "border-slate-200 hover:border-slate-300"
                  }`}
                >
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-500 rounded-lg flex items-center justify-center">
                      <Sparkles className="w-5 h-5 text-white" />
                    </div>
                    <div>
                      <h4 className="font-bold text-slate-900">AI Contract Flow</h4>
                      <Badge className="text-xs bg-emerald-100 text-emerald-700">GPT-4o</Badge>
                    </div>
                  </div>
                  <p className="text-sm text-slate-600">
                    Automatically generate a contract from your conversation and get instant risk analysis.
                  </p>
                </button>

                {/* Template Option */}
                <button
                  onClick={() => setMode("template")}
                  className={`p-6 rounded-xl border-2 text-left transition-all ${
                    mode === "template" 
                      ? "border-blue-500 bg-blue-50" 
                      : "border-slate-200 hover:border-slate-300"
                  }`}
                >
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-10 h-10 bg-slate-600 rounded-lg flex items-center justify-center">
                      <FileText className="w-5 h-5 text-white" />
                    </div>
                    <h4 className="font-bold text-slate-900">Template-Based</h4>
                  </div>
                  <p className="text-sm text-slate-600">
                    Extract terms from chat and fill in a standard contract template manually.
                  </p>
                </button>
              </div>

              <Button 
                onClick={mode === "ai" ? runAiFlow : analyze} 
                disabled={loading}
                className="w-full bg-blue-600 hover:bg-blue-700 h-12"
              >
                {loading ? (
                  <>
                    <LoadingAnimation className="w-5 h-5 mr-2" />
                    {mode === "ai" ? "Generating Contract & Analyzing..." : "Analyzing Chat..."}
                  </>
                ) : mode === "ai" ? (
                  <>
                    <Sparkles className="w-5 h-5 mr-2" />
                    Generate AI Contract
                  </>
                ) : (
                  "Extract Terms from Chat"
                )}
              </Button>
            </div>
          )}

          {/* Step 3: AI Flow Review (Draft + Analysis) */}
          {step === 3 && aiFlowResult && (
            <div className="space-y-6">
              {/* Parties */}
              {aiFlowResult.parties && (
                <div className="flex items-center gap-4 p-3 bg-slate-50 rounded-lg">
                  <span className="text-sm text-slate-600">
                    <strong>Investor:</strong> {aiFlowResult.parties.investor}
                  </span>
                  <span className="text-slate-300">|</span>
                  <span className="text-sm text-slate-600">
                    <strong>Agent:</strong> {aiFlowResult.parties.agent}
                  </span>
                </div>
              )}

              {/* Risk Summary */}
              {analysis && (
                <div className={`p-4 rounded-xl border-2 ${
                  analysis.overallRisk === 'High' ? 'bg-red-50 border-red-200' :
                  analysis.overallRisk === 'Medium' ? 'bg-yellow-50 border-yellow-200' :
                  'bg-emerald-50 border-emerald-200'
                }`}>
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <Shield className="w-5 h-5" />
                      <span className="font-bold">Contract Guardian Analysis</span>
                    </div>
                    <Badge className={
                      analysis.overallRisk === 'High' ? 'bg-red-100 text-red-800' :
                      analysis.overallRisk === 'Medium' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-emerald-100 text-emerald-800'
                    }>
                      {analysis.overallRisk || 'Unknown'} Risk
                    </Badge>
                  </div>

                  {/* Red Flags */}
                  {analysis.redFlags?.length > 0 && (
                    <div className="mb-3">
                      <div className="text-sm font-semibold text-red-900 mb-1 flex items-center gap-1">
                        <AlertTriangle className="w-4 h-4" />
                        Red Flags
                      </div>
                      <ul className="text-sm text-red-800 space-y-1">
                        {analysis.redFlags.slice(0, 3).map((flag, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span>•</span>
                            <span>{flag}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Recommendations */}
                  {analysis.recommendations?.length > 0 && (
                    <div>
                      <div className="text-sm font-semibold text-blue-900 mb-1 flex items-center gap-1">
                        <CheckCircle className="w-4 h-4" />
                        Recommendations
                      </div>
                      <ul className="text-sm text-blue-800 space-y-1">
                        {analysis.recommendations.slice(0, 3).map((rec, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span>→</span>
                            <span>{rec}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}

              {/* Draft Preview */}
              <div>
                <Label className="text-sm font-semibold mb-2 block">Generated Contract Draft</Label>
                <textarea 
                  className="w-full h-64 border border-slate-300 rounded-lg p-4 text-sm font-mono bg-slate-50" 
                  value={draft}
                  onChange={(e) => setDraft(e.target.value)}
                />
              </div>

              <div className="flex justify-between">
                <Button variant="outline" onClick={() => setStep(1)}>
                  Start Over
                </Button>
                <div className="flex gap-3">
                  <a 
                    href={`data:text/markdown;charset=utf-8,${encodeURIComponent(draft)}`}
                    download="contract_draft.md"
                    className="px-4 py-2 text-sm border border-slate-300 rounded-lg hover:bg-slate-50 flex items-center"
                  >
                    Download .md
                  </a>
                  <Button 
                    onClick={onClose}
                    className="bg-emerald-600 hover:bg-emerald-700"
                  >
                    Done
                  </Button>
                </div>
              </div>
            </div>
          )}

          {/* Step 2: Edit Terms */}
          {step === 2 && (
            <div className="space-y-6">
              <div>
                <Label className="text-sm font-semibold mb-2 block">Contract Template</Label>
                <select 
                  className="w-full border border-slate-300 rounded-lg px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={templateId} 
                  onChange={(e) => setTemplateId(e.target.value)}
                >
                  <option value="">Select a template</option>
                  {CONTRACT_TEMPLATES.map(t => (
                    <option key={t.id} value={t.id}>{t.name}</option>
                  ))}
                </select>
              </div>

              {analysis?.plain_summary && (
                <div className="bg-slate-50 rounded-lg p-4 border border-slate-200">
                  <div className="text-xs font-semibold text-slate-500 mb-1">AI Analysis</div>
                  <p className="text-sm text-slate-700">{analysis.plain_summary}</p>
                </div>
              )}

              <div>
                <Label className="text-sm font-semibold mb-2 block">Contract Terms</Label>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-h-96 overflow-y-auto border border-slate-200 rounded-lg p-4 bg-slate-50">
                  {Object.entries(terms).map(([k, v]) => (
                    <div key={k} className="flex flex-col">
                      <Label className="text-xs text-slate-600 mb-1">{k}</Label>
                      <Input 
                        value={v ?? ""} 
                        onChange={(e) => updateTerm(k, e.target.value)}
                        className="text-sm"
                      />
                    </div>
                  ))}
                  {missing.map(k => (
                    <div key={k} className="flex flex-col">
                      <Label className="text-xs text-rose-600 mb-1 flex items-center gap-1">
                        <AlertCircle className="w-3 h-3" />
                        {k} (required)
                      </Label>
                      <Input 
                        value={terms[k] ?? ""} 
                        onChange={(e) => updateTerm(k, e.target.value)}
                        className="text-sm border-rose-300 focus:ring-rose-500"
                      />
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex justify-between">
                <Button variant="outline" onClick={() => setStep(1)}>
                  Back
                </Button>
                <Button 
                  onClick={generate} 
                  disabled={saving}
                  className="bg-blue-600 hover:bg-blue-700"
                >
                  {saving ? (
                    <>
                      <LoadingAnimation className="w-4 h-4 mr-2" />
                      Generating...
                    </>
                  ) : (
                    "Generate Contract Draft"
                  )}
                </Button>
              </div>
            </div>
          )}

          {/* Step 4: Preview & Download */}
          {step === 4 && (
            <div className="space-y-4">
              <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4">
                <p className="text-sm text-emerald-900 font-medium">
                  ✓ Contract draft generated successfully
                </p>
              </div>

              <div>
                <Label className="text-sm font-semibold mb-2 block">Preview (Markdown)</Label>
                <textarea 
                  className="w-full h-80 border border-slate-300 rounded-lg p-4 text-sm font-mono bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-500" 
                  value={draft} 
                  readOnly 
                />
              </div>

              <div className="flex justify-between">
                <a 
                  href={`data:text/markdown;charset=utf-8,${encodeURIComponent(draft)}`}
                  download="contract_draft.md"
                  className="px-4 py-2 text-sm border border-slate-300 rounded-lg hover:bg-slate-50"
                >
                  Download .md
                </a>
                <div className="flex gap-3">
                  <Button variant="outline" onClick={() => setStep(2)}>
                    Edit Terms
                  </Button>
                  <Button 
                    onClick={onClose}
                    className="bg-emerald-600 hover:bg-emerald-700"
                  >
                    Done
                  </Button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}